### ISSUE TITLE
PA Flow - Create reminder cards in planner for tasks in the WIP bucket

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/development_projects#15]
# Description

Each day at 5:00 AM, this flow calculates the number of days since creation for each Planner task in `SPH Cannell Private/Cannell Tasks/👨‍💻WIP - No Due Date`. It creates a reminder task in `SPH Cannell Private/Cannell Tasks/🙋‍♂️ Reminders` if the difference between the day it was created and today is a multiple of 7.

## Development notes

This flow is meant to replace the "email list of tasks with no due date" flow attached below.
* Emails are easy to overlook, ignore, or delete without even opening.
* Can I have Power Automate create a task reminder every X number of days from the task creation time?
* This would also allow me to use tasks with due dates for actual due dates.

# Tasks

- [x] Copy [Prod - Create reminder cards in Planner for Next tasks](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/379b1358-83ba-434a-938a-fded3bc525f0/details) and modify to work for the 👨‍💻WIP - No Due Date
- [ ] Is there a way to turn off "Show on card?" [Notes on this topic](https://github.com/brad-cannell/power_automate/wiki/Planner-Step)

## After updates

You can reuse these whenever you make updates.

- [x] Change daysSinceCreatedTest back to 7 (if applicable)
- [x] Update the description (if applicable)
- [x] Export the flow, add it to OneDrive, delete the old flow, and push to GitHub

# Links

* [Power automate](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows)
* [Prod - Create reminder cards in Planner for WIP tasks](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/98e5af37-a0ac-4d8b-bfb9-bdab76ebdb4b/details)

# Relationships

Works with #3
Works with #13 
Works with #14 
Replaces #4

**Comment by mbcann01** [comment]
2024-11-26: Turned this flow off. It wasn't very helpful.
