### ISSUE TITLE
PA Flow - Weekly check-in emails

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/development_projects#20]
# Overview

We would like to have weekly asynchronous check-ins with our team members. At a high level, we want to automatically send each team member a list of check-in questions each week, record their answers, and generate a report with their responses. 

This issue doesn't isn't for a single Power Automate flow. There are [multiple Power Automate flows](#power-automate) that help us accomplish the entire check-in process. Currently, the process works like this.

**Steps:**

* Each week, we send each team member an email that contains a [Form](https://forms.office.com/pages/designpagev2.aspx?lang=en-US&origin=OfficeDotCom&route=Start&subpage=design&id=JG0ye61BV0-8YInkpqxyG71AiY1PcFFApnv5JfiYoF1UOUIwUDJNUEdGSkFCVjM1WlIwQjNYN1dXTCQlQCN0PWcu) that contains some questions about their upcoming week. (Forms and Power Automate)

* When they complete the form, their responses are saved in a SharePoint list. (Power Automate and Lists)

* Brad is sent an email with each team member's responses. Until we have a report (and maybe even after we have a report), this seems like the easiest way to send a follow-up email. (Power Automate)

* We extract those responses from the list and use them to generate a report. Under construction. (Power BI)

* The report can be emailed out for review and follow-up. Under construction.

### Student affairs team

* The [form](https://forms.office.com/pages/designpagev2.aspx?lang=en-US&origin=OfficeDotCom&route=Start&subpage=design&id=JG0ye61BV0-8YInkpqxyG71AiY1PcFFApnv5JfiYoF1UOUIwUDJNUEdGSkFCVjM1WlIwQjNYN1dXTCQlQCN0PWcu) is active.

* The [flow](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/76a41006-7e69-45cf-9bcb-7344c9973bc3/details) to send out the form is active.
  * Tuesday at 1:30 PM

* The [flow](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/4e52687f-d44c-4d42-a802-c26c67c7ab68/details) to add form responses to the SharePoint list is active.

* Brad is sent an email with each team member's responses that he can easily use to send a follow-up email.

* There is still no automated report mechanism.

### Research team

* The [form](https://forms.office.com/pages/designpagev2.aspx?lang=en-US&origin=OfficeDotCom&route=Start&subpage=design&id=JG0ye61BV0-8YInkpqxyG8z39yWCm1tOvRvt05WVrJ1UMU1PRVg4WjlDN1g3V1ZITEJBMVMyS0ZJUSQlQCN0PWcu) is active.

* The [flow](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/c7dceee7-5e77-44b1-9996-97861bf04423/details) to send out the form is active.
  * Wednesday at 1:30 PM

* The [flow]() to add form responses to the SharePoint list is active.

* Brad and James are sent an email with each team member's responses that they can easily use to send a follow-up email.

* There is still no automated report mechanism.

## Team members

Currently, we are inviting members of the following teams to complete check-ins.

* [The student affairs team](https://uthtmc.sharepoint.com/sites/SPHDallasStudentAffairsPrivate/Lists/Student%20Affairs%20Team/AllItems.aspx?env=WebViewList)
* [The research team](https://uthtmc.sharepoint.com/sites/SPHCannellResearch/Lists/Research%20Team/AllItems.aspx?env=WebViewList)

At some point in the future, we may decide to check in with other groups (e.g., students working on a thesis or ILE) in a similar fashion.

## Timing

According to at least one [resource](https://www.hugo.team/blog/best-day-for-team-meetings-not-monday#:~:text=The%20end%20of%20the%20weekend,having%20them%20on%20Monday%20mornings.), it looks like Tuesday afternoons are the best time to do a check-in. However, I think it also depends on what other interactions you have with the team throughout the week.

# Tasks 

## Left off at

2023-02-25: Working on using Qualtrics instead of Forms. 
* I can send Qualtrics surveys with personal links from Power Automate.
* I can automatically add Quatrics responses to an Excel sheet or SharePoint list.
* I still haven't figured out how to keep our SharePoint directory synced with the Qualtrics contact list.
* I still haven't figured out how to pipe in the previous week's goals to this week's check-in.

2023-02-18: Working on the report in Power BI. See tasks there.
* You don’t need to have the Power BI dashboard done to start using this flow.
* And for now, you may just want to keep the results stored in CSV files - not SharePoint lists. You should be able to use the CSV files in PowerBI, but also in Excel and R. And you can use permissions to lock down/hide the CSV file.

## Task list

- [x] Email the Form to the team.
- [x] Add responses to SharePoint.
- [x] Send Brad an email with the check-in responses when each person completes their check-in.
- [ ] Set the the team member's address as the sender address so that I can hit `reply` instead of `forward` when I respond.
- [ ] Create a report. Right now, we are working on creating a report in Power BI. It has to be built in Windows.
- [ ] Create a flow that creates a report from the check-in results.
- [ ] Add a list of people who haven't completed the check-in.

## Next steps

- [ ] See if you can get branching to work so that you don't have to make multiple copies of all of the forms and flows. 
- [ ] Figure out how to pipe in last week's goals so that you can ask if they completed them or not.
- [ ] Instead of having a separate list for each team, can I have a master list that pulls the correct people for a given purpose?

## Versioning

⭐️ Power Automate doesn't have a built-in versioning system. Don't forget to save versions for your flows to the Power Automate GitHub repository.

🏷️ Also, try to remember to add a version tag to the Power Automate repo when you make changes to the flows.

# Links

Currently, we use multiple forms, flows, and lists to accomplish the entire check-in process. At some point in the future, we may want to try to combine some of these flows.

## Forms

* [My Forms](https://www.office.com/launch/forms?auth=2)

* [Student Affairs Team Weekly Check-In](https://forms.office.com/pages/designpagev2.aspx?lang=en-US&origin=OfficeDotCom&route=Start&subpage=design&id=JG0ye61BV0-8YInkpqxyG71AiY1PcFFApnv5JfiYoF1UOUIwUDJNUEdGSkFCVjM1WlIwQjNYN1dXTCQlQCN0PWcu)

* [Research Team Weekly Check-In](https://forms.office.com/pages/designpagev2.aspx?lang=en-US&origin=OfficeDotCom&route=Start&subpage=design&id=JG0ye61BV0-8YInkpqxyG8z39yWCm1tOvRvt05WVrJ1UMU1PRVg4WjlDN1g3V1ZITEJBMVMyS0ZJUSQlQCN0PWcu)

### Forms resources 

* [Recurring forms: Survey your team to check in and stay connected](https://support.microsoft.com/en-us/office/survey-your-team-to-check-in-and-stay-connected-4ebf181b-9a0d-4921-a477-5954e94cfa04)

* [Extracting Data From Forms Into SharePoint](https://blog.crgroup.com/power-up-with-power-apps-extracting-data-from-microsoft-forms-into-sharepoint/)

## Power Automate

* [Prod - Weekly check-in emails student affairs team](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/76a41006-7e69-45cf-9bcb-7344c9973bc3/details). Each week, this flow sends out an email to team members asking them to complete a check-in using Microsoft Forms.

* [Prod - When a new response is submitted - Add to List - Student Affairs Team](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/4e52687f-d44c-4d42-a802-c26c67c7ab68/details). When a new response is submitted to the Student Affairs Team Weekly Check-in Form - Add the response information to a SharePoint List.

* [Prod - Weekly check-in emails research team](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/c7dceee7-5e77-44b1-9996-97861bf04423/details. EEach week, this flow sends out an email to team members asking them to complete a check-in using Microsoft Forms.

* [Prod - When a new response is submitted - Add to List - Research Team](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/6a82f115-367d-4dee-b831-14afe096b1ed/details). When a new response is submitted to the Student Affairs Team Weekly Check-in Form - Add the response information to a SharePoint List. Also sends Brad and James emails with responses.

### Power Automate resources

* [Power Automate repo wiki](https://github.com/brad-cannell/power_automate/wiki). At some point, any useful information should be stored here.

## Lists

* [Student Affairs Team directory](https://uthtmc.sharepoint.com/sites/SPHDallasStudentAffairsPrivate/Lists/Student%20Affairs%20Team/AllItems.aspx?env=WebViewList)

* [Student Affairs Team Weekly Check-In](https://uthtmc.sharepoint.com/sites/SPHDallasStudentAffairsPrivate/Lists/Student%20Affairs%20Team%20Weekly%20CheckIn/AllItems.aspx?env=WebViewList) 

* [Research Team directory](https://uthtmc.sharepoint.com/sites/SPHCannellResearch/Lists/Research%20Team/AllItems.aspx?env=WebViewList)

* [Research Team Weekly Check-In](https://uthtmc.sharepoint.com/sites/SPHCannellResearch/Lists/Research%20Team%20Weekly%20CheckIn/AllItems.aspx?env=WebViewList).

### Lists for development and testing

* [Master People List](https://uthtmc.sharepoint.com/sites/SPHCannellPrivate/Lists/Master%20People%20List/AllItems.aspx?env=WebViewList)

* [DETECT Team Directory](https://uthtmc.sharepoint.com/sites/SPHDETECT-RPC/Lists/DETECT%20Team%20Directory/AllItems.aspx?env=WebViewList)

* [Test Team Directory](https://uthtmc-my.sharepoint.com/personal/michael_b_cannell_uth_tmc_edu/Lists/Test%20Team%20Directory/AllItems.aspx?env=WebViewList)

* [Test Weekly Check-in](https://uthtmc.sharepoint.com/sites/SPHCannellPrivate/Lists/Test%20Weekly%20Checkin/AllItems.aspx?env=WebViewList)

## SharePoint

* [SPH Dallas Student Affairs](https://uthtmc.sharepoint.com/sites/SPHDallasStudentAffairsPrivate)

* [SPH Cannell Research](https://uthtmc.sharepoint.com/sites/SPHCannellResearch)

* [SPH DETECT](https://uthtmc.sharepoint.com/sites/SPHDETECT-RPC/SitePages/ProjectHome.aspx)

## Qualtrics

* [Qualtrics page in PA wiki](https://github.com/brad-cannell/power_automate/wiki/Qualtrics)

* [Qualtrics IDs](https://uthtmc.az1.qualtrics.com/Q/QualtricsIdsSection/IdsSection)

* [Test Weekly Check-in Survey](https://uthtmc.az1.qualtrics.com/survey-builder/SV_0TVWcRTrN3EmOlE/edit)

* [Test Contact List](https://uthtmc.az1.qualtrics.com/iq-directory/#/POOL_4GzzubfTPaRp6g1/groups/lists/CG_1oA3s2iYEqSKQRD)

* [Workflow - Test Post new survey results to Power Automate](https://uthtmc.az1.qualtrics.com/workflows/ui/SV_0TVWcRTrN3EmOlE/SV_0TVWcRTrN3EmOlE/list/OC_R90HRqaZS9h1de1/editor)

* [SB - Qualtrics create and email personal links](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/4bcd446e-33a2-4923-b72a-8aa676490e26/details)

* [SB - Getting Qualtrics data into Power Automate](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/2e933034-6e16-4978-b63a-f1de37f2df06/details)

# Example Questions

## Check-in question resources

* [Some example check-in questions](https://www.hugo.team/blog/40-check-in-questions-for-meetings)

* [A Manager’s Guide for Holding Effective Weekly Check-ins](https://www.yac.com/blog/weekly-check-in#:~:text=Key%20takeaways,-It's%20important%20to&text=Weekly%20check%2Dins%20help%20build,on%20their%20calendar%20each%20week.) 

* [What’s the Best Day for Team Meetings?](https://www.hugo.team/blog/best-day-for-team-meetings-not-monday#:~:text=The%20end%20of%20the%20weekend,having%20them%20on%20Monday%20mornings.). It looks like Tuesday early afternoon may be the best time to do weekly check-ins.

## Fun

I'd like to add fun questions, but not until I can figure out how to add them randomly. Or maybe I'll have to update them manually each week. Don't worry about this yet.

* If you could only talk to one person for a whole week, and it had to be one of your colleagues, who would it be?
* If you had to work full-time for a month while located in the last place you vacationed, could you do it?
* What superpower would allow you to complete your work ten times faster?
* If you could invent an app that would help our organization in any way you want, what would your app do?
* If you listen to music while working, what kind of music is it?
* What’s something that made you laugh while working?

## Productivity

* What are you working on this week?
* What challenges (if any) are you facing this week?
* What can be improved on this week compared to the previous week?
* What are you looking forward to working on?
* How did you feel about this week?
* Is there anyone you’d like to give kudos to?
* What is your goal for the week?
* What takes up most of your time?
* What milestones have you hit?
* How can I better support your work?
* What excites you about your work? What has you worried?
* How does your work here align with your career goals?
* How do you feel about your team?
* Do you feel supported by leadership?

## Mental Health

* Using a percentage, how full is your plate right now?
* How is your work-life balance this week?
* What’s going well at work right now? What isn’t?
* Do you have time to get the rest you need?
* How are you doing?
* Do you have enough support right now?
* How can we support you better on this task?

## Other ideas

* We may want to consider using prompts from the 7 habits guided journal each week.

# Questions

Can we set up recurrence directly in Forms? 
* No. We have to use Power Automate

Can we set up a question pool and have Forms select X questions from the pool each week at random? 
* No. As a workaround, we can potentially create multiple different forms and have Power Automate randomly select an entire form to send (or at least send them on a rotating basis).

Can Forms results be saved to a SharePoint list instead of an Excel file? 
* Yes. See link with instructions below.

Can we condition branching logic on a response to a likert scale question? 
* [No](https://answers.microsoft.com/en-us/msoffice/forum/all/using-branching-on-likert-scale-questions-in-ms/fa2fe0c1-f54b-414b-b74a-2a1099bc62b1). Potential alternatives include adding likert response options to a multiple choice question or potentially using Qualtrics.

When should we do the weekly check-in?
* [What’s the Best Day for Team Meetings?](https://www.hugo.team/blog/best-day-for-team-meetings-not-monday#:~:text=The%20end%20of%20the%20weekend,having%20them%20on%20Monday%20mornings.). It looks like Tuesday early afternoon may be the best time to do weekly check-ins.

**Comment by mbcann01** [comment]
This is what was on ClickUp: Weekly check-in. Each Friday, please give a brief update on what you've accomplished this week and what you plan to work on next week. Also, please share any successes or barriers you've experienced.

And: What did you work on this week? What do you plan to work on next week? Successes? Challenges?

**Comment by mbcann01** [comment]
Left off at trying to embed an iframe into the email.

**Comment by mbcann01** [comment]
I got the Qualtircs API to work!! When a survey is filled out, it automatically updates my SharePoint List. Once I have it in the list, I can do many different things with the information.

**Comment by mbcann01** [comment]
One potential downside to using Qualtrics is the difficulty in getting the user information (e.g., name, email) into my SharePoint list. 

* If I use a Qualtrics survey link, it's anonymous. 
* If I use email addresses, then I have to send the emails directly from Qualtrics, which I don't think I want to do. 

So, maybe I will go back to using Forms tomorrow.

**Comment by mbcann01** [comment]
Left off at experimenting with [this flow](https://make.powerautomate.com/environments/Default-7b326d24-41ad-4f57-bc60-89e4a6ac721b/flows/4e52687f-d44c-4d42-a802-c26c67c7ab68/details). Why aren't all of the forms I created options in the `When a new response is submitted` trigger?

**Comment by mbcann01** [comment]
You don’t need to have the Power BI dashboard done to start using this flow. 
And for now, you may just want to keep the results stored in CSV files - not SharePoint lists. You should be able to use the CSV files in PowerBI, but also in Excel and R. And you can use permissions to lock down/hide the CSV file.

**Comment by mbcann01** [comment]
# Notes on first week in use

Did a first pilot test of the check-in this week and I'm going over the results this morning. I think it is working ok, but I will definitely need a way to filter by week in the future and a way to more easily respond to the comments they leave for me. I kind for wish there was an interactive form we could use. Maybe Power BI can be used this way?

**Comment by mbcann01** [comment]
# New ideas

Have the flow that adds weekly check-in responses to lists also send me an email with the responses embedded. Have the subject line be "weekly check-in follow-up". That way I can easily forward responses to the team member.
* Can I automatically get the question names and responses? That way, I won’t have to manually change the PA flow in the future if I change up the questions.
* Would be even better if we could remind them of their goals from the previous week and ask them if they were accomplished.
    * Is it possible to pipe text into Forms?
    * If not, I think this may be possible in Qualtrics.
* Potential ways around anonymous Qualtrics links.
    * Low tech: have them select their name from a drop-down list.
    * High tech: Use Power Automate and the Qualtrics API to send the survey to their email address and associate the email address with their survey.
