### ISSUE TITLE
My Status Dashboard

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/development_projects#33]
# Overview

**Move a lot of the text below! For the sake of expediency, I've been brain-dumping a lot of information, thoughts, and tasks into this issue card. However, much of that brain dump hasn't been specifically about my dashboard, which compliments my larger deep work process, but is also distinct from my larger deep work process. When time allows, you need to move a lot of this stuff to a more appropriate place.**

I'm always looking for more efficient and effective ways to engage in strategic planning and manage my time. This is a running task that helps me track the tweaks I make to my process over time.

Strategic planning and My Status Dashboard are important components of my SharePoint homepage, but my homepage is bigger than just my status dashboard. Additionally, I may not always use SharePoint for my status dashboard. Therefore, I created a separate task for my SharePoint homepage generally (#9).

2024-01-02
- My Status Dashboard currently lives in [SharePoint](https://uthtmc.sharepoint.com/sites/SPHCannellPrivate/SitePages/My-Status-Dashbord.aspx?csf=1&web=1&e=1pbqz8).
- I'm trying to incorporate what I've learned from Deep Work into my strategic planning and my dashboard. There are a bunch of notes in Apple Notes about Deep Work.
- **At some point, I think it became more complicated than it needed to be**. At this point, I don't think I need an entirely new method for tracking tasks from scratch. At this point, the only thing I'm missing is a way to track leading and lagging indicators as a means to evaluate different approaches to scheduling. Start there today. You can add more complexity later if there's a good reason to. For now, I think you can leave priorities and goals as text narrative.
- I don't know if I will always use SharePoint or not. For now, just get a usable system and set of goals in place for the Spring. You can always improve things later.

## Links

- [Google Drive Personal Productivity folder](https://drive.google.com/drive/folders/1IdmxYVBipiK9dUAB-XsQR8mDFazxM7wo?ths=true). I think this is where I will end up putting all the documentation this year, but I'm not completely sure yet.
- [Old Status Update SOP](https://uthtmc.sharepoint.com/:w:/r/sites/SPHCannellPrivate/_layouts/15/Doc.aspx?sourcedoc=%7B3998E95E-0D5D-436C-97AD-7E68CD362557%7D&file=Status%20Updates.docx&action=default&mobileredirect=true). I haven't had time to read it over closely yet, but there may be some stuff in there that I want to continue to use. If nothing else, I need to delete it if I'm not going to continue to use it.
- YouTube video: [Cal's planning system](https://www.youtube.com/watch?v=3FipKTzkTD4).

## Technologies I'm using
I need to take stock of all of the technologies I'm using. Additionally, I should consider the pros and cons of condensing some of them.

- SharePoint. The primary touchpoint for my status dashboard.
- Apple Notes. This is where my daily and weekly plans live.
- Planner. Dumping ground for tasks.
  - Should I try Apple Reminders?
- Word. SOPs and Meeting Minutes are written in Planner.
- GitHub. Some tasks and some stuff in the wikis. I LOVE GitHub, but the [wikis can't be accessed from the mobile app](https://github.com/orgs/community/discussions/9566).
- Timular. Time tracking.
- Excel. Deep Work strategy tracking (not built yet).

## Deep Work Tracker

This may eventually need to be its own task. 

- Create a simple tracker in Excel. Test using on phone. You can make it better later. Start with the example from [Medium](https://medium.com/@FILWD/quantifying-and-visualizing-deep-work-af4689a62423).
  - Use Power Automate to create a "log entry" button.
  - Use Power Apps to create a weekly update log.
  - Create a dashboard and visualize trends using Power BI.
  - Or do all of the above with Shiny.

## SharePoint
I'm currently using SharePoint as my primary touchpoint for strategic planning and housing a status dashboard. This section contains notes on the pros and cons of using SharePoint for this purpose.

- **Pros**
  - My SharePoint homepage is the first thing I see when I open my browser each day. Although, I could easily embed or link a Google Doc or Word document into my SharePoint homepage.
- **Cons**
  - I don't like that I have to click on the Dropdown menu at the top of the screen to jump between sections of My Status Dashboard. For example, from Overview to Goals to Projects, etc.
  - Can't make comments or tooltips.
  - Not transportable if I leave UTH; although, that seems pretty unlikely to happen.

I wonder how it would feel to just use Word and Excel instead of SharePoint. I can still embed or link to Word and Excel from within SharePoint.

# Tasks

- [ ] Figure out what to do Monday. Work backward from annual goals.
- [ ] Write out a draft SOP. It doesn't have to be perfect right now.
- [ ] Create a simple tracker in Excel. Test using on phone. You can make it better later. Start with the example from Medium.
- [ ] Make a strategic planning SOP.
- [ ] I need to write a better overview section. At a high level, what is the purpose of My Status Dashboard? How do I use My Status Dashboard?
- [ ] Add instructions for starting each day. time blocking works, but only if you use it.
- [ ] Create a list for status updates. Maybe make it in lists or maybe just make it in Excel.
- [ ] Decide if you want to keep using Apple Notes for your weekly and daily plans. If not, update the instructions on the overview page. Whatever you decide to use, track it in an SOP with a justification.
- [ ] Add quarterly goals to the Goals page.
- [ ] Figure out if you can add tooltips or hover messages to text in SharePoint.
- [ ] Polish the annual objectives section. Including deciding what technologies to use.
- [ ] Polish the quarterly objectives section. Including deciding what technologies to use.
- [ ] Replace the projects overview planner board. It isn't helpful at all.
- [ ] Having a team member directory is interesting, but is it a part of my status dashboard? Give this some thought.
- [ ] Make a technology comparison spreadsheet. All else being equal, use the least complicated, most flexible tool available.

**Comment by mbcann01** [comment]
2024-01-02
- I reviewed the current status dashboard in SharePoint, I moved over the hand-written notes from Johnson City, and I created some tasks for improvements (listed below).
- The next step is to make sure I have a plan I can start executing.
- Then, I would like a way to track my progress. Start simple and only increase complexity if there is a real need to do so.

**Comment by mbcann01** [comment]
2024-01-03
- Working on my Deep Work tracker.
- Move over priorities and goals.

**Comment by mbcann01** [comment]
2024-01-04

- Working on my [Personal Productivity SOP](https://docs.google.com/document/d/1VIodLwMERZ0mJUPbCEDpgrZIjo_wx_3KN0KY1RmxU70/edit)
- Working on my [Deep Work Tracker](https://docs.google.com/spreadsheets/d/1wVfspQPIteFDXjqj5qIOxLNSHrG-dD4KgynfLXGDVSg/edit#gid=1688299392)

Tomorrow, I need to get to a place where I know what to do Monday to start making meaningful progress. 

I think that means **working backward from my annual goals to create quarterly and weekly goals**. Daily goals will be written directly in my calendar. By the end of the day tomorrow, I need to be able to answer the question, "**What do I need to work on Monday/next week?**"

After I know what to work on next week, I can figure out where to write it all down and track it.
- Possiblility
  - Instructions in Google Docs, linked in SharePoint. Even if you put instructions on a SharePoint page, it will still be a link. 
  - Annual goals in Planner
  - Weekly goals in Planner
  - Daily goals in Calendar
  
I think it would be really confusing to have annual goals in Google Sheets, weekly goals in Apple Notes or Planner, and daily goals in Apple Notes or Planner. Just give adding everything to Planner for a week a try. 

Why not start with Google Sheets instead of Planner? Because Planner is where all my individual tasks live, and it allows me to turn email into tasks, which can be really handy. I want everything to live in as few places as possible. 

Once I know what to do next week, and where to store my tasks, I can write out the process/SOP for doing a weekly check-in and start thinking about some metrics for tracking leading and lagging indicators (please try to keep it simple for now!!!)

**Comment by mbcann01** [comment]
2024-01-05

- [x] Set quarterly and weekly goals.

**Move a lot of the text above! For the sake of expediency, I've been brain-dumping a lot of information, thoughts, and tasks into this issue card. However, much of that brain dump hasn't been specifically about my dashboard, which compliments my larger deep work process, but is also distinct from my larger deep work process. When time allows, you need to move a lot of this stuff to a more appropriate place.**
